name: absensi
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.3
  device_info_plus: ^9.1.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  latlong2: ^0.9.0
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
